CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  original_video_url TEXT,
  status TEXT NOT NULL DEFAULT 'upload',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clips (
  id SERIAL PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  start_time NUMERIC NOT NULL,
  end_time NUMERIC NOT NULL,
  title TEXT,
  hook TEXT,
  score INTEGER,
  video_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS transcript_job_id TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS transcript JSONB;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS segments JSONB;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS reasoning TEXT;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS caption_style TEXT NOT NULL DEFAULT 'karaoke';
ALTER TABLE clips ADD COLUMN IF NOT EXISTS effects JSONB;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS loop JSONB;
